language: node_js
node_js:
- node
deploy:
  provider: heroku
  api_key:
    secure: U0HVn4aSG2bPBFpfH7J2r81VkQRiJ5aA/KTE6hhg1U/3/OWUIJWzve8dAOw15xcjq8LBrvLZ6ri9i7u2yd/5hHOD8RmNKZq41XacAfQzLIpiWXT8W6C1/SZ3rXWSphWIFLE+ZCEvQZfSviRcfNuJKb7qIYBcEL6rBWLY6QngnNqVtaklpIyvww6JikufuzcZGMY7xBoUHNaMKfVw8thGfB94FU4H3peSw18fcPol5/QdzaMqa/b9nhWPLnY74QS8bmNKLkTENG3aR63sWIvEHcipjigm+sxAqznb3WFoJ5wGcBD25njuj5C36p/gf5MGFwZfiGjqTGgVy7JLPX9n08QCOUAslVYPzGM/Htm9X3lw2YyhG+KKt9y8CfIyG+HwakwYMjyd/tdp3BHYNRHVIj1o7LWsjbdLsA6/+ZRFdyRRWGuy39VdECel2uY45KVid6GpCb1oE8gIgd7FicC91uzI5JXroXs1+dKuI7ev1U9sIHbW2GV9TY3toWu35Tw4R3PwOKtpBdOuVrRLDw09ad1hJC8QZr4mKJgImHFwCHuNd0Jv82T1Mr4hpzb/DDcVQ/HhmRndLLIzAZBkwUJw+7jQ43trl9Bz2iv1+IJIHWe3/0oNf8jOr3pTITLb/0CpgEIxb3IsR64FezWqXrK+mSCePBoGEMIJJ6bFMOc+pL0=
  app: cctraveltracker
  skip_cleanup: true